BatchJobMonitor:
  class: BatchJobMonitor
  cron: "* * * * *" # minutely

CommitMonitor:
  class: CommitMonitor
  cron: "*/5 * * * *" # every 5th minute

GithubNotificationMonitorWorker:
  class: GithubNotificationMonitorWorker
  cron: "* * * * *" # minutely

PullRequestMonitor:
  class: PullRequestMonitor
  cron: "*/5 * * * *" # every 5th minute

StaleIssueMarker:
  class: StaleIssueMarker
  cron: "0 0 * * 1" # midnight every Monday
