source 'https://rubygems.org'

gem 'octokit',       '~> 1.25.0'
gem 'minigit',       '~> 0.0.4'
gem 'ruby_bugzilla', '~> 0.4.1'
gem 'rails_config',  '0.5.0.beta1'

# Lock down dependency
gem 'faraday', '~> 0.8.8'
