#!/bin/bash

export RAILS_ENV=production
export PATH=/opt/miq_bot:$PATH

function urlescape() {
  PAYLOAD="$1" ruby -rcgi -e "puts CGI.escape(ENV['PAYLOAD'])"
}

safeuser=$(urlescape ${DATABASE_USER})
safepass=$(urlescape ${DATABASE_PASSWORD})
if [ -z "${safeuser}" -o -z "${safepass}" ]; then
  DATABASE_USERINFO=""
else
  DATABASE_USERINFO="${safeuser}:${safepass}@"
fi

export DATABASE_URL="postgresql://${DATABASE_USERINFO}${DATABASE_HOSTNAME:-localhost}:${DATABASE_PORT:-5432}/${DATABASE_NAME:-miq_bot_production}?encoding=utf8&pool=25&wait_timeout=5"
