#!/bin/bash

source /usr/local/bin/container_env

mkdir /root/.ssh
cp /root/ssh/* /root/.ssh/
chown 600 /root/.ssh/miq-bot

pushd /opt/miq_bot/config
  ln -s /opt/miq_bot_data/github_notification_monitor.yml

  ln -s /run/secrets/config/master.key
  ln -s /run/secrets/config/settings.local.yml
popd

[[ -n $QUEUE_NAME ]] && COMMAND="sidekiq -q $QUEUE_NAME"
[[ -z $COMMAND ]] && COMMAND="rails server"

cd /opt/miq_bot

bundle exec rake db:create
bundle exec rake db:migrate
bundle exec rake assets:precompile

exec bundle exec ${COMMAND}
